package proyecto1.ventanas;

import grafos.GrafoLista;
import javax.swing.JPanel;

/**
 *
 * @author dilan
 */
public class GrafoVentana extends javax.swing.JFrame {

    GrafoLista grafo;

    /**
     * Creates new form Grafo
     *
     * @param grafo grafo que aparecera en la interfaz
     * @param anchoTabla el ancho que tendra la tabla generada
     */
    public GrafoVentana(GrafoLista grafos, int anchoTabla, int altoTabla) {
        this.grafo = grafos;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Laberinto");
        gererarPanel(anchoTabla, altoTabla);
    }

    public void gererarPanel(int anchoTabla, int altoTabla) {
        int alto, ancho, inicialX, inicialY;
        inicialX = 160;//pocision inicial en x de la celda 1
        inicialY = 20;//pocision inicial en y de la celda 1
        alto = 50;//alto de la celda
        ancho = 50;//ancho de la celda
        int nodo = 0;//contador del nodo al que va
        //System.out.println("\nnodos: ");
        for (int i = 0; i < altoTabla; i++) {
            int auxX = inicialX;
            for (int j = 0; j < anchoTabla; j++) {
                int top = 1, left = 1, button = 1, right = 1;
                JPanel nodo1 = new JPanel();
                //System.out.println(grafo.getVertices()[nodo].getDato());
                if (grafo.isIn(nodo, nodo - 1)) { //verifica si el nodo anterior esta en la unido si no es asi borra el borde izquirdo
                    left = 0;
                }
                if (grafo.isIn(nodo, nodo + 1) ) {
                    System.out.println("");
                    right = 0;
                }
                if (grafo.isIn(nodo, nodo - anchoTabla)) {
                    top = 0;
                }
                if (grafo.isIn(nodo, nodo + altoTabla) ){
                    button = 0;
                }
                nodo1.setBorder(javax.swing.BorderFactory.createMatteBorder(top, left, button, right, new java.awt.Color(51, 51, 51)));
                jPanel1.add(nodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(auxX, inicialY, ancho, alto));
                auxX = auxX + ancho;
                nodo++;
            }
            inicialY = inicialY + alto;
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
