package proyecto1.ventanas;

import grafos.GrafoLista;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author dilan/yoita5
 */
public class GrafoVentana extends javax.swing.JFrame {

    private InicioVentana ventanaAnterior;
    private GrafoLista grafo;
    private JPanel[] celdas; //se utiliza para luego dibujar la solucion

    /**
     * Creates new form Grafo
     *
     * @param grafo grafo que aparecera en la interfaz
     * @param anchoTabla el ancho que tendra la tabla generada
     */
    public GrafoVentana(GrafoLista grafos, int anchoTabla, int altoTabla, InicioVentana ventanAnterior) {
        this.grafo = grafos;
        this.ventanaAnterior = ventanAnterior;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Laberinto");
        gererarPanel(anchoTabla, altoTabla);
    }

    public void gererarPanel(int anchoTabla, int altoTabla) {
        JPanel[] celdasNuevas = new JPanel[grafo.getVertices().length];
        int alto, ancho, inicialX, inicialY;
        inicialX = 0;//pocision inicial en x de la celda 1
        inicialY = 0;//pocision inicial en y de la celda 1
        alto = 40;//alto de la celda
        ancho = 40;//ancho de la celda
        int nodo = 0;//contador del nodo al que va
        //System.out.println("\nnodos: ");
        for (int i = 0; i < altoTabla; i++) {
            int auxX = inicialX;
            for (int j = 0; j < anchoTabla; j++) {
                int top = 2, left = 2, button = 2, right = 2;
                JPanel nodo1 = new JPanel();
                //System.out.println(grafo.getVertices()[nodo].getDato());
                if (grafo.isIn(nodo, nodo - 1)) { //verifica si el nodo anterior esta en la unido si no es asi borra el borde izquirdo
                    left = 0;
                }
                if (grafo.isIn(nodo, nodo + 1)) {
                    right = 0;
                }
                if (grafo.isIn(nodo, nodo - anchoTabla)) {
                    top = 0;
                }
                if (grafo.isIn(nodo, nodo + anchoTabla)) {
                    button = 0;
                }
                nodo1.setPreferredSize(new Dimension(1500, 1500));
                if (grafo.getFirst() == nodo) {
                    nodo1.setBorder(javax.swing.BorderFactory.createMatteBorder(top, left, button, right, new java.awt.Color(0, 143, 57)));
                }else if(grafo.getLast() == nodo){
                    nodo1.setBorder(javax.swing.BorderFactory.createMatteBorder(top, left, button, right, new java.awt.Color(255, 0, 0)));
                } else {
                    nodo1.setBorder(javax.swing.BorderFactory.createMatteBorder(top, left, button, right, new java.awt.Color(51, 51, 51)));
                }
                jPanel1.add(nodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(auxX, inicialY, ancho, alto));
                auxX = auxX + ancho;
                celdasNuevas[nodo] = nodo1;
                nodo++;
            }
            inicialY = inicialY + alto;
        }
        this.celdas = celdasNuevas;
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        botonSolucion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel1);

        volver.setText("Volver a generar");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        botonSolucion.setText("Mostrar Solucion");
        botonSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volver)
                .addGap(183, 183, 183)
                .addComponent(botonSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSolucion)
                    .addComponent(volver))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * Elimina de la lista int los elementos repetidos
    **/
//    private Lista reducirCamino(Lista lista){
//        Integer[] listaArray = lista.toArray();
//        Lista auxRecorrido = new Lista();
//        Lista auxRepetidos = new Lista();
//        int repitiendo = -1;
//        for (int i = 0; i < lista.length(); i++) {
//            if (auxRecorrido.haveThis(listaArray[i])) {
//                auxRepetidos.append(listaArray[i]);
//            }
//            auxRecorrido.append(listaArray[i]);
//        }
//        System.out.println("lista recorrido: " );
//        auxRecorrido.mostrar();
//        System.out.println("Repetidos: ");
//        auxRepetidos.mostrar();
//        
//        auxRecorrido.vaciar();
//        
//        for (int i = 0; i < lista.length(); i++) {
//            if (auxRepetidos.haveThis(listaArray[i])) {
//                if (repitiendo == i) {
//                    repitiendo = -1;
//                }
//                else{
//                    repitiendo = listaArray[i];
//                }  
//            }else if(repitiendo != -1){
//                System.out.println("nada");
//            }
//            else{
//                auxRecorrido.append(listaArray[i]);
//            }
//        }
//        
//        return auxRecorrido;
//    }
    
    private void botonSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSolucionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"No disponible por el momento");
//        Lista camino = grafo.getCamino();
//        System.out.println("el camino es:");
//        camino.mostrar();
//        Nodo aux = camino.getFirst();
//        while(aux!=null){
//            celdas[aux.getElemento()].setBackground(Color.MAGENTA);
//            aux = aux.getSiguiente();
//            pack();  
//        }
        
    }//GEN-LAST:event_botonSolucionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSolucion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
