package proyecto1.ventanas;

import grafos.GrafoLista;

/**
 *
 * @author dilan/yoita5
 */
public class InicioVentana extends javax.swing.JFrame {

    /**
     * Creates new form InicioVentana
     */
    public InicioVentana() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Generar Laberinto");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jOptionPane1 = new javax.swing.JOptionPane();
        textArea1 = new java.awt.TextArea();
        jColorChooser1 = new javax.swing.JColorChooser();
        label2 = new java.awt.Label();
        errorMensaje = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        nColumnas = new javax.swing.JTextField();
        nFilas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonGenerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ErrorMensaje = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        verde1 = new javax.swing.JLabel();
        rojo = new javax.swing.JLabel();

        label1.setText("label1");

        label2.setText("label2");

        errorMensaje.setForeground(new java.awt.Color(255, 0, 0));

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(166, 216, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 102)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(nColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, -1));
        jPanel1.add(nFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 90, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Ancho que tendra el laberinto: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Largo que tendra el laberinto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 190, -1));

        botonGenerar.setText("Generar");
        botonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Por favor introduce:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 140, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Generar Laberinto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 230, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText(" Se generará un laberinto en base al ancho y el largo dado. ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 380, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("  -El lado con bordes de color               es la entrada del laberinto.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 350, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("  -El lado con bordes de color            es la salida del laberinto.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 350, 10));

        ErrorMensaje.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.add(ErrorMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 290, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("Instrucciones:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        verde1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        verde1.setForeground(new java.awt.Color(51, 215, 83));
        verde1.setText("verde");
        verde1.setToolTipText("");
        jPanel1.add(verde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 290, 20));

        rojo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rojo.setForeground(new java.awt.Color(229, 25, 19));
        rojo.setText("rojo");
        rojo.setToolTipText("");
        jPanel1.add(rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 240, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarActionPerformed
        // TODO add your handling code here:
        try {
            int columnas = Integer.parseInt(nColumnas.getText());
            int filas = Integer.parseInt(nFilas.getText());
            if (columnas <= 0 || filas <= 0) {
                System.out.println("numero de columnas o filas invalida");
                ErrorMensaje.setText("Numero de columnas o filas invalida");
            }else if (columnas <=5 || filas <= 5) {
                System.out.println("numero de columnas o filas invalida");
                ErrorMensaje.setText("Numero de columnas o filas no puede ser menor a 5");
            }
            else{
                nColumnas.setText("");
                nFilas.setText("");
                int nNodos = filas * columnas; //numero de nodos que tendra el grafo a generar

                GrafoLista grafo2 = new GrafoLista(nNodos);
                grafo2.generarTabla(columnas, filas);
                grafo2.mostrarLog();

                GrafoLista arbolGrafo = grafo2.prims();
                this.setVisible(false);
                GrafoVentana ventana = new GrafoVentana(arbolGrafo, columnas, filas, this);//interfaz de laberinto
                ventana.setVisible(true);
     
            }
       
            
        } catch (NumberFormatException e) {
            System.out.println(e);
            errorMensaje.setText("Error: no se pueden introducir letras");
        }


    }//GEN-LAST:event_botonGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMensaje;
    private javax.swing.JButton botonGenerar;
    private javax.swing.JLabel errorMensaje;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField nColumnas;
    private javax.swing.JTextField nFilas;
    private javax.swing.JLabel rojo;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    private javax.swing.JLabel verde1;
    // End of variables declaration//GEN-END:variables
}
