package proyecto1.ventanas;

import grafos.GrafoLista;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author dilan/yoita5
 */
public class GrafoVentana extends javax.swing.JFrame {

    private InicioVentana ventanaAnterior;
    private GrafoLista grafo;

    /**
     * Creates new form Grafo
     *
     * @param grafo grafo que aparecera en la interfaz
     * @param anchoTabla el ancho que tendra la tabla generada
     */
    public GrafoVentana(GrafoLista grafos, int anchoTabla, int altoTabla, InicioVentana ventanAnterior) {
        this.grafo = grafos;
        this.ventanaAnterior = ventanAnterior;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Laberinto");
        gererarPanel(anchoTabla, altoTabla);
    }

    public void gererarPanel(int anchoTabla, int altoTabla) {
        int alto, ancho, inicialX, inicialY;
        inicialX = 0;//pocision inicial en x de la celda 1
        inicialY = 0;//pocision inicial en y de la celda 1
        alto = 40;//alto de la celda
        ancho = 40;//ancho de la celda
        int nodo = 0;//contador del nodo al que va
        //System.out.println("\nnodos: ");
        for (int i = 0; i < altoTabla; i++) {
            int auxX = inicialX;
            for (int j = 0; j < anchoTabla; j++) {
                int top = 1, left = 1, button = 1, right = 1;
                JPanel nodo1 = new JPanel();
                //System.out.println(grafo.getVertices()[nodo].getDato());
                if (grafo.isIn(nodo, nodo - 1)) { //verifica si el nodo anterior esta en la unido si no es asi borra el borde izquirdo
                    left = 0;
                }
                if (grafo.isIn(nodo, nodo + 1)) {
                    right = 0;
                }
                if (grafo.isIn(nodo, nodo - anchoTabla)) {
                    top = 0;
                }
                if (grafo.isIn(nodo, nodo + anchoTabla)) {
                    button = 0;
                }
                nodo1.setPreferredSize(new Dimension(1500, 1500));
                if (grafo.getFirst() == nodo) {
                    nodo1.setBorder(javax.swing.BorderFactory.createMatteBorder(top, left, button, right, new java.awt.Color(52, 64, 235)));
                }else if(grafo.getLast() == nodo){
                    nodo1.setBorder(javax.swing.BorderFactory.createMatteBorder(top, left, button, right, new java.awt.Color(255, 0, 0)));
                } else {
                    nodo1.setBorder(javax.swing.BorderFactory.createMatteBorder(top, left, button, right, new java.awt.Color(51, 51, 51)));
                }
                jPanel1.add(nodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(auxX, inicialY, ancho, alto));
                auxX = auxX + ancho;
                nodo++;
            }
            inicialY = inicialY + alto;
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel1);

        volver.setText("Volver a generar");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(383, Short.MAX_VALUE)
                .addComponent(volver)
                .addGap(373, 373, 373))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volver)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
